---
schema: ${GRAPHQL_SCHEMA:./graphql.schema.json}
documents:
  # Intentionally avoid the generated documents to prevent a feedback loop.
  - 'apps/nextjs/{lib,src}/**/*.{graphql,ts,tsx}'
extensions:
  codegen:
    overwrite: true
    ignoreNoDocuments: true # <- for better experience with the watcher
    generates:
      'apps/nextjs/gql/':
        preset: 'client'
        plugins: []
      './graphql.schema.json':
        plugins: ['introspection']
    hooks:
      afterAllFileWrite: ['prettier --write']
