packageExtensions:
  '@graphql-codegen/cli@*':
    peerDependencies:
      '@types/node': '^18'
      ts-node: '^10'
      typescript: '~4.8.4'
  '@graphql-eslint/eslint-plugin@*':
    peerDependencies:
      '@types/node': '^18'
      typescript: '~4.8.4'
  graphql-config@*:
    peerDependencies:
      '@types/node': '^18'
      typescript: '~4.8.4'

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

yarnPath: .yarn/releases/yarn-4.0.0-rc.27.cjs
