enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      'ts-node': '*'
      typescript: ^4.8.4
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      'cosmiconfig-typescript-loader': '*'
      '@types/node': '*'
      cosmiconfig: '*'
      cosmiconfig-toml-loader: '*'
      ts-node: '*'
      typescript: ^4.8.4
  '@graphql-tools/graphql-tag-pluck@^7':
    dependencies:
      '@babel/core': '*'
  graphql-config@*:
    dependencies:
      '@types/node': '*'
      cosmiconfig-toml-loader: '*'
      ts-node: '*'
      typescript: ^4.8.4
  '@whatwg-node/fetch@*':
    dependencies:
      '@types/node': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.39.cjs
