enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      typescript: ^4.8.4
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      '@types/node': '*'
      cosmiconfig: '*'
      cosmiconfig-toml-loader: '*'
      cosmiconfig-typescript-loader: '*'
      ts-node: '*'
      typescript: ^4.8.4
  '@graphql-tools/graphql-tag-pluck@^7':
    dependencies:
      '@babel/core': '*'
  '@roots/bud-entrypoints@*':
    dependencies:
      webpack: ^5
  '@roots/bud-stylelint@*':
    dependencies:
      webpack: ^5
  '@roots/eslint-config@*':
    dependencies:
      prettier: '*'
      webpack: ^5
  '@whatwg-node/fetch@*':
    dependencies:
      '@types/node': '*'
  graphql-config@*:
    dependencies:
      '@types/node': '*'
      cosmiconfig-toml-loader: '*'
      ts-node: '*'
      typescript: ^4.8.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.40.cjs
