enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  '@graphql-tools/graphql-tag-pluck@^7':
    dependencies:
      '@babel/core': '*'
  cosmiconfig-typescript-loader@*:
    dependencies:
      '@types/node': '*'
      'ts-node': '*'
      typescript: '^4.8.4'
  lucide-react@^0.104.0:
    dependencies:
      prop-types: '*'
  ts-node@*:
    dependencies:
      '@types/node': '*'
      typescript: '^4.8.4'
