enableTelemetry: false
nodeLinker: node-modules

packageExtensions:
  '@graphql-codegen/cli@^2.16.0':
    dependencies:
      cosmiconfig-toml-loader: '*'
  '@graphql-codegen/cli@^2.15.0':
    dependencies:
      '@types/node': '*'
      ts-node: '*'
      typescript: ^4.8.4
  '@graphql-tools/graphql-tag-pluck@^7':
    dependencies:
      '@babel/core': '*'
  graphql-config@^4.4.0:
    dependencies:
      cosmiconfig-toml-loader: '*'
      cosmiconfig-typescript-loader: '*'
      ts-node: '*'
  graphql-config@^4.3.6:
    dependencies:
      '@types/node': '*'
      typescript: ^4.8.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.35.cjs
