# https://github.com/numtide/treefmt/wiki

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = []

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
    "*.tsx",
]
excludes = []

[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """

##: 1) shellcheck
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

##: 2) format
shfmt -i 2 -s -w "$@"

    """,
    "--", # bash swallows the second argument when using -c
]
includes = ["*.sh"]
excludes = []
