# SPDX-FileCopyrightText: 2022-2023 Temple University
#
# SPDX-License-Identifier: GPL-3.0-or-later

# https://github.com/numtide/treefmt/wiki

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = []

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.jsx",
  "*.json",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.tsx",
]
# TODO: auto-exclude generated files (via nixago?)
excludes = [".wp-env.json"]

[formatter.shell]
command = "sh"
options = [
  "-eucx",
  """

##: 1) shellcheck
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

##: 2) format
shfmt -i 2 -s -w "$@"

    """,
  "--", # bash swallows the second argument when using -c
]
includes = ["*.sh"]
excludes = []
