#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2022 Temple University
# SPDX-License-Identifier: GPL-3.0-or-later

# shellcheck disable=1091
. "$(dirname -- "$0")/_/husky.sh"

# FIXME
# reuse lint

yarn turbo test

# FIXME: the wp-env instance should not be necessary here, but until
# there's a live environment, there's no other graphql endpoint
yarn workspace wordpress-app wp-env start
yarn turbo build
