version: '3'
name: nextjs-wordpress

services:
  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --accesslog
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: wordpress:php8.1
    restart: always
    depends_on:
      - mysql
    volumes:
      - wp-data:/var/www/html
      - ./.env:/var/www/html/.env
      - ./wp-content:/var/www/html/wp-content
      - ../../packages/nextjs-wordpress-plugin:/var/www/html/wp-content/plugins/nextjs-wordpress-plugin
      - ../../packages/nextjs-wordpress-theme:/var/www/html/wp-content/themes/nextjs-wordpress-theme
    expose:
      - 80
      - 443
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_URL}`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', false);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_DEBUG_LOG', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('HEADLESS_FRONTEND_URL', '${HEADLESS_FRONTEND_URL}');
        define('PREVIEW_SECRET_TOKEN', '${PREVIEW_SECRET_TOKEN}');
        define('WP_SITEURL', 'https://${WORDPRESS_URL}');
        define('WP_HOME', 'https://${WORDPRESS_URL}');

  wpcli:
    image: wordpress:cli-php8.1
    depends_on:
      - mysql
      - wordpress
    working_dir: /var/www/html
    volumes:
      - wp-data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./.env:/var/www/html/.env
      - ./setup.sh:/var/www/html/setup.sh
    user: xfs
    command: >
      /bin/sh -c '
      sleep 30;
      chmod +x setup.sh;
      ./setup.sh;
      tail -f /dev/null;
      '
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}

volumes:
  db-data: {}
  wp-data: {}
